package org.sagebionetworks.bridge.models.templates;

public enum TemplateType {
    EMAIL_ACCOUNT_EXISTS,
    EMAIL_APP_INSTALL_LINK,
    EMAIL_RESET_PASSWORD,
    EMAIL_SIGN_IN,
    EMAIL_SIGNED_CONSENT,
    EMAIL_VERIFY_EMAIL,
    SMS_ACCOUNT_EXISTS,
    SMS_APP_INSTALL_LINK,
    SMS_PHONE_SIGN_IN,
    SMS_RESET_PASSWORD,
    SMS_SIGNED_CONSENT,
    SMS_VERIFY_PHONE;
}
