repos:
-   repo: https://github.com/awslabs/git-secrets
    rev: 80230af
    hooks:
        -   id: git-secrets
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
        -   id: check-added-large-files
        -   id: trailing-whitespace
        -   id: check-merge-conflict
