package org.sagebionetworks.bridge.models;

public enum TemplateType {
    ACCOUNT_EXISTS_EMAIL,
    ACCOUNT_EXISTS_SMS,
    APP_INSTALL_LINK_EMAIL,
    APP_INSTALL_LINK_SMS,
    EMAIL_SIGN_IN_EMAIL,
    PHONE_SIGN_IN_SMS,
    RESET_PASSWORD_EMAIL,
    RESET_PASSWORD_SMS,
    SIGNED_CONSENT_EMAIL,
    SIGNED_CONSENT_SMS,
    VERIFY_EMAIL_EMAIL,
    VERIFY_PHONE_SMS;
}
